# Generated by Django 5.0.14 on 2025-05-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='horavisita',
            field=models.TimeField(blank=True, db_column='horavisita', null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='horavisita',
            field=models.TimeField(blank=True, db_column='horavisita', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='descsol',
            field=models.TextField(db_column='descsol'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estadosol',
            field=models.CharField(db_column='estadosol', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='fechavisita',
            field=models.DateField(db_column='fechavisita'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='nrofac',
            field=models.IntegerField(blank=True, db_column='nrofac', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='nrosol',
            field=models.AutoField(db_column='nrosol', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='ruttec',
            field=models.CharField(blank=True, db_column='ruttec', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tiposol',
            field=models.CharField(db_column='tiposol', max_length=20),
        ),
    ]
