# Generated by Django 5.0.14 on 2025-05-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_factura_horavisita_solicitudservicio_horavisita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='horavisita',
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='horavisita',
        ),
    ]
